### ISSUE TITLE
not working with bokeh 0.12.10

### ISSUE THREAD

**Issue by dadokkio** [zjffdu/bkzep#2]
Hi,
I've just tried to use your package with zeppelin 0.7.0 and bokeh 0.12.10.
It raises the following error:

```
>>from bokeh.plotting import output_notebook, show, figure
>>import bkzep
>>output_notebook(notebook_type='zeppelin')

[..]
File "/opt/miniconda3/envs/test/lib/python3.6/site-packages/bkzep/io.py", line 20, in <module>
    from bokeh.embed import notebook_div, server_document
ImportError: cannot import name 'notebook_div'
```

I need to downgrade bokeh or a support for this release is planned?
Thanks

**Comment by zjffdu** [comment]
Thanks @dadokkio seems bokeh 0.12.10 change its API, I will fix it and make a new release.
Thanks again for trying bokeh on apache zeppelin, welcome any comments and feedback.

**Comment by zjffdu** [comment]
@dadokkio It has been fixed, and I make a new release 0.4.0 which support both all the versions after bokeh 0.12.7

**Comment by dadokkio** [comment]
Thanks for the fix. It works properly.
I'm gonna edit bokeh notebook guide suggesting to use your package to integrate zeppelin and bokeh.
